// Generated by CoffeeScript 1.8.0
(function() {
  var controller;

  controller = {};

  controller.index = function(req, res) {
    res._cc.fail("Invalid route, please use the UI at loves.money or view github source for valid requests.");
  };

  module.exports = controller;

}).call(this);

//# sourceMappingURL=index.js.map
