// Generated by CoffeeScript 1.8.0
(function() {
  var IndexController;

  IndexController = (function() {
    function IndexController() {}

    IndexController.getIndex = function(req, res) {
      res._cc.fail("Invalid route, please use the UI at loves.money or view github source for valid requests.");
    };

    return IndexController;

  })();

  module.exports = IndexController;

}).call(this);

//# sourceMappingURL=IndexController.js.map
