// Generated by CoffeeScript 1.8.0
(function() {
  var CorsHandler, DynamicViewsHandler, ErrorHandler, MiddlewaresLoader, ModelsLoader, MultiViews, RoutesLoader, app, bodyParser, browserify, config, cookieParser, express, favicon, logger, path, views, _;

  browserify = require('browserify-middleware');

  express = require('express');

  path = require('path');

  favicon = require('serve-favicon');

  _ = require('lodash');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  MultiViews = require('multi-views');

  config = require('./config/config.js');

  ErrorHandler = require('./core/handlers/error-handler.js');

  CorsHandler = require('./core/handlers/cors-handler.js');

  DynamicViewsHandler = require('./core/handlers/dynamic-views-handler.js');

  ModelsLoader = require('./core/loaders/waterline-loader.js');

  RoutesLoader = require('./core/loaders/routes-loader.js');

  MiddlewaresLoader = require('./app/middlewares/loader.js');

  app = express();

  app.disable('x-powered-by');

  app.use(function(req, res, next) {
    res.setHeader('X-Powered-By', 'Endless river of sweat and tears');
    next();
  });

  app.use('*.coffee', function(req, res, next) {
    var err;
    console.log("[Blocked] Access to coffeescript %s %s", req.method, req.url);
    err = ErrorHandler.createError('Forbidden', {
      status: 403
    });
    next(err);
  });

  app.use("/public", express["static"](path.join(__dirname, 'public')));

  app.use("/core", express["static"](path.join(__dirname, 'public', 'core')));

  app.use("/vendor", express["static"](path.join(__dirname, 'public', 'vendor')));

  app.use("/js", express["static"](path.join(__dirname, 'public', config.appDir, 'js')));

  app.use("/css", express["static"](path.join(__dirname, 'public', config.appDir, 'css')));

  app.use("/img", express["static"](path.join(__dirname, 'public', config.appDir, 'img')));

  app.use("/partials", express["static"](path.join(__dirname, 'public', config.appDir, 'partials')));

  app.use("/templates", express["static"](path.join(__dirname, 'public', config.appDir, 'templates')));

  app.set('config', config);

  MiddlewaresLoader.registerMiddlewares(app);

  app.use(app.get('middlewares')['redirector']);

  app.use(favicon(path.join(__dirname, 'public', config.appDir, 'img', 'favicon.ico')));

  app.use(cookieParser());

  app.use(bodyParser.json({
    extended: false
  }));

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(CorsHandler.allowDomain('*'));

  app.use(ErrorHandler.resRenderer);

  ModelsLoader.initialize(app, config.db);

  MultiViews.setupMultiViews(app);

  DynamicViewsHandler.setupViews(app, [path.join(__dirname, config.appDir, 'views', 'default'), path.join(__dirname, 'core', 'views', 'default')]);

  app.use("/public", ErrorHandler.displayAppError(ErrorHandler.createError('Not Found', {
    status: 404
  })));

  app.use("/core", ErrorHandler.displayAppError(ErrorHandler.createError('Not Found', {
    status: 404
  })));

  app.use("/vendor", ErrorHandler.displayAppError(ErrorHandler.createError('Not Found', {
    status: 404
  })));

  app.use("/js", ErrorHandler.displayAppError(ErrorHandler.createError('Not Found', {
    status: 404
  })));

  app.use("/css", ErrorHandler.displayAppError(ErrorHandler.createError('Not Found', {
    status: 404
  })));

  app.use("/img", ErrorHandler.displayAppError(ErrorHandler.createError('Not Found', {
    status: 404
  })));

  app.use("/partials", ErrorHandler.displayAppError(ErrorHandler.createError('Not Found', {
    status: 404
  })));

  app.use("/templates", ErrorHandler.displayAppError(ErrorHandler.createError('Not Found', {
    status: 404
  })));

  app.use(logger(config.env === 'development' ? 'dev' : 'tiny'));

  RoutesLoader.loadRoutes(path.join(__dirname, config.appDir, 'routes'));

  RoutesLoader.registerRoutes(app);

  views = app.get('views');

  app.use(ErrorHandler.createAppError('Not Foundx', {
    status: 404
  }));

  app.use(ErrorHandler.displayAppError());

  module.exports = app;

}).call(this);

//# sourceMappingURL=server.js.map
