// Generated by CoffeeScript 1.8.0
(function() {
  var ErrorHandler, LmErrorHandler,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ErrorHandler = require('../../core/handlers/error-handler.js');

  LmErrorHandler = (function(_super) {
    __extends(LmErrorHandler, _super);

    function LmErrorHandler() {
      return LmErrorHandler.__super__.constructor.apply(this, arguments);
    }

    LmErrorHandler.resRenderer = function(req, res, next) {
      LmErrorHandler.__super__.constructor.resRenderer.call(this, req, res, function() {});
      res.success = res._cc.success;
      res.fail = res._cc.fail;
      next();
    };

    return LmErrorHandler;

  })(ErrorHandler);

  module.exports = LmErrorHandler;

}).call(this);

//# sourceMappingURL=ErrorHandler.js.map
