// Generated by CoffeeScript 1.8.0
(function() {
  var AuthJwt, MiddlewaresLoader, eh, lovesMoneyRedirector;

  eh = require('../../core/handlers/error-handler.js');

  AuthJwt = require('./auth-jwt.js');

  lovesMoneyRedirector = require('./redirector.js');

  MiddlewaresLoader = (function() {
    function MiddlewaresLoader() {}

    MiddlewaresLoader.middlewares = {
      'jwt-verify': AuthJwt.verify,
      'jwt-verify-admin': AuthJwt.verifyAdmin,
      'redirector': lovesMoneyRedirector
    };

    MiddlewaresLoader.registerMiddlewares = function(app) {
      return app.set('middlewares', MiddlewaresLoader.middlewares);
    };

    return MiddlewaresLoader;

  })();

  module.exports = MiddlewaresLoader;

}).call(this);

//# sourceMappingURL=loader.js.map
