// Generated by CoffeeScript 1.8.0
(function() {
  var eh, redirector;

  eh = require('../../core/handlers/error-handler.js');

  redirector = function(req, res, next) {
    var aliases, requestAlias, _ref;
    if (req.headers.host && ((_ref = req.headers.host) !== 'loves.money' && _ref !== 'www.loves.money' && _ref !== 'api.loves.money')) {
      requestAlias = req.headers.host.replace(/\.loves\.money$/, '');
      aliases = req.app.models.alias;
      aliases.findOne({
        src_name: requestAlias
      }, function(err, alias) {
        if (err) {
          err = eh.createError('Unable to get alias', {
            status: 500
          });
          next(err);
        }
        if (alias) {
          if (alias.dest_domain.match(/^(ht|f)tps?:\/\//)) {
            res.redirect(alias.dest_domain);
          } else {
            res.redirect('http://' + alias.dest_domain);
          }
        } else {
          err = eh.createError('Alias not found', {
            status: 404
          });
          next(err);
        }
      });
    } else {
      next();
    }
  };

  module.exports = redirector;

}).call(this);

//# sourceMappingURL=redirector.js.map
