// Generated by CoffeeScript 1.8.0
(function() {
  var CorsHandler;

  CorsHandler = (function() {
    function CorsHandler() {}

    CorsHandler.allowDomain = function(domain) {
      if (typeof domain === "undefined" || domain === '') {
        throw new Error("The first parameter must be a string representing the domain");
      }
      return function(req, res, next) {
        res.header('Access-Control-Allow-Origin', domain);
        res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE');
        res.header('Access-Control-Allow-Headers', 'Content-Type');
        next();
      };
    };

    return CorsHandler;

  })();

  module.exports = CorsHandler;

}).call(this);

//# sourceMappingURL=cors-handler.js.map
