// Generated by CoffeeScript 1.8.0
(function() {
  var RoutesLoader, Waterline, WaterlineMysqlAdapter, path, walk,
    __hasProp = {}.hasOwnProperty;

  walk = require('fs-walk');

  path = require("path");

  Waterline = require('waterline');

  WaterlineMysqlAdapter = require('sails-mysql');

  RoutesLoader = {};

  RoutesLoader.orm = new Waterline;

  RoutesLoader.updateAdapters = function(dbConfig) {
    var adapter, key, _ref;
    console.log('Updating DB adapters');
    _ref = dbConfig.adapters;
    for (key in _ref) {
      if (!__hasProp.call(_ref, key)) continue;
      adapter = _ref[key];
      if (adapter === 'mysqlAdapter') {
        dbConfig.adapters[key] = WaterlineMysqlAdapter;
      }
    }
    return dbConfig;
  };

  RoutesLoader.loadModels = function(modelsDir) {
    console.log('Loading models');
    walk.walkSync(modelsDir, function(basedir, filename, stat) {
      var re, schemaJson;
      re = /(?:\.([^.]+))?$/;
      if ((filename.indexOf(".") !== 0) && (filename.indexOf("_") !== 0) && (re.exec(filename)[1] === "json")) {
        console.log(' - ' + filename);
        schemaJson = require(path.join(basedir, filename));
        return RoutesLoader.orm.loadCollection(Waterline.Collection.extend(schemaJson));
      }
    });
    return RoutesLoader;
  };

  module.exports = RoutesLoader;

}).call(this);

//# sourceMappingURL=waterline-loader.js.map
