// Generated by CoffeeScript 1.8.0
(function() {
  var DynamicViewsHandler, RoutesGroupFactory, SubdomainsHandler, express,
    __hasProp = {}.hasOwnProperty;

  express = require('express');

  SubdomainsHandler = require('../handlers/subdomain-handler.js');

  DynamicViewsHandler = require('../handlers/dynamic-views-handler.js');

  RoutesGroupFactory = {};

  RoutesGroupFactory.createRouter = function(file) {
    var router, routesConfig;
    routesConfig = require(file);
    router = {};
    router.registerRoutes = function(app) {
      var config, controllerFileName, controllerMethods, controllerRouter, error, key, route, routes, routesController, routesGroup, _ref, _ref1;
      routes = {};
      config = app.get('config');
      _ref = routesConfig.routesGroups;
      for (key in _ref) {
        if (!__hasProp.call(_ref, key)) continue;
        routesGroup = _ref[key];
        controllerFileName = routesGroup.controller;
        if (routes[controllerFileName] == null) {
          controllerRouter = express.Router();
          controllerMethods = require('../../' + config.appDir + '/' + routesConfig.controllerPath + '/' + controllerFileName);
          controllerRouter.controllerMethods = controllerMethods;
          routes[controllerFileName] = controllerRouter;
          if (routesConfig.viewPath) {
            routesController = DynamicViewsHandler.attachControllerViews(routesConfig.viewPath, routes[controllerFileName]);
          } else {
            routesController = DynamicViewsHandler.attachControllerViews(false, routes[controllerFileName]);
          }
        }
        _ref1 = routesGroup.routes;
        for (key in _ref1) {
          if (!__hasProp.call(_ref1, key)) continue;
          route = _ref1[key];
          try {
            routes[controllerFileName][route.method](route.url, routes[controllerFileName]['controllerMethods'][route.handler]);
          } catch (_error) {
            error = _error;
            console.log('Error registering route ' + route.handler + '.' + route.method);
            throw error;
          }
        }
        if (routesConfig.subdomain == null) {
          routesConfig.subdomain = '';
        }
        app.use(routesGroup.prefix, SubdomainsHandler(routesConfig.subdomain, routesController));
      }
      return true;
    };
    return router;
  };

  module.exports = RoutesGroupFactory;

}).call(this);

//# sourceMappingURL=router-factory.js.map
