// Generated by CoffeeScript 1.8.0
(function() {
  var IndexController;

  IndexController = (function() {
    function IndexController() {}

    IndexController.index = function(req, res) {
      res.render("index");
    };

    IndexController.about = function(req, res) {
      res.render("about");
    };

    IndexController.contact = function(req, res) {
      res.render("contact");
    };

    IndexController.demo = function(req, res) {
      res.render("demo");
    };

    IndexController.pricing = function(req, res) {
      res.render("pricing");
    };

    return IndexController;

  })();

  module.exports = IndexController;

}).call(this);

//# sourceMappingURL=IndexController.js.map
