// Generated by CoffeeScript 1.8.0
(function() {
  var IndexController;

  IndexController = (function() {
    function IndexController() {}

    IndexController.index = function(req, res) {
      res.render("index", {
        title: "loves.money - BETA - domain and email forwarding service"
      });
    };

    return IndexController;

  })();

  module.exports = IndexController;

}).call(this);

//# sourceMappingURL=IndexController.js.map
