// Generated by CoffeeScript 1.8.0
(function() {
  var controller;

  controller = {};

  controller.index = function(req, res) {
    res.render("index", {
      title: "loves.money - BETA - domain and email forwarding service"
    });
  };

  module.exports = controller;

}).call(this);

//# sourceMappingURL=index.js.map
